[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
