[build]
  command = "npm install && npm run build"
  publish = "public"
  environment = { SECRETS_SCAN_OMIT_PATHS = ".env.example,README.md,README_BUSINESS.md,railway.toml,uploads/*,Dockerfile" }

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = ".env.example,README.md,README_BUSINESS.md,railway.toml,uploads/*,Dockerfile"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
