[build]
nixpacks = true

[build.nixpacksConfig]
builder = "nodejs"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"

[environments.development.variables]
NODE_ENV = "development"