[build]
nixpacks = true

[build.nixpacksConfig]
builder = "nodejs"

[build.nixpacksConfig.variables]
NODE_VERSION = "18"

[build.nixpacksConfig.phases.setup]
cmds = ["npm ci"]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"

[environments.development.variables]
NODE_ENV = "development"