name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        uses: railway/cli@v3
        with:
          command: 'deploy'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        # This will deploy to Railway using the Railway CLI
        # You need to create a Railway token and add it as a GitHub secret